DefaultContentLanguage = "ja"
languageCode = "ja-JP"
hasCJKLanguage = true

baseURL = "/"
title = "なぜかサイバーと呼ばれています"
theme = "hugo_theme_robust"

googleAnalytics = "UA-81696512-2"

[Params]
#  description = "趣味のカメラや旅行、コンピュータの話などを気まぐれで。"
  twitter_cards = true
  readmore = true
  enableHighlight = true # highlight.js option

[Params.author]
thumbnail = "images/author.jpg"
name = "yussi"
description = "<p>趣味はコンピュータ、カメラ、ラジオ、鉄道旅行など。思いついたことを適当に書きます。</p>"
twitter = "https://twitter.com/yussi_macs"
github = "https://github.com/yussi"

[outputs]
page = [ "HTML", "AMP" ] # if you want AMP enable.

[taxonomies]
category = "categories"